-- モグラパニック！ ランキング用テーブル
-- Supabase → SQL Editor に貼り付けて Run

create table if not exists public.rankings (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 12),
  score integer not null check (score >= 0),
  difficulty text not null default 'normal',
  created_at timestamptz not null default now()
);

create index if not exists rankings_score_desc_idx
  on public.rankings (score desc, created_at desc);

alter table public.rankings enable row level security;

drop policy if exists "rankings_public_read" on public.rankings;
create policy "rankings_public_read"
  on public.rankings for select
  using (true);

drop policy if exists "rankings_public_insert" on public.rankings;
create policy "rankings_public_insert"
  on public.rankings for insert
  with check (true);
